# Tmux Configuration

# vim binding
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
# Mac
set -s copy-command 'pbcopy'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'

# Status bar styling
set -g status-style 'bg=#1E1E2E'

# Custom key bindings for scripts
# f: Fuzzy find and switch to project directory
bind-key f run-shell "tmux neww ~/.config/script/tmux-sessionizer.sh"



bind-key e run-shell "tmux neww tv tmux-sessions"


# h: Open frequently visited websites
# g: Switch to main session
bind-key m run-shell "tmux neww ~/.config/script/spotify-sessionizer.sh"

bind-key g run-shell "tmux switch-client -t main"

# x: Kill current pane without confirmation
bind-key x kill-pane

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
